name: Secret Scan
on: [pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect Secrets
        uses: reviewdog/action-detect-secrets@v1
        with:
          reporter: github-pr-check
          fail_on_error: true
